apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-ui
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - clusters: {}
  template:
    metadata:
      name: 'app-ui-{{.nameNormalized}}'
    spec:
      project: default
      source:
        chart: nginx
        repoURL: https://charts.bitnami.com/bitnami
        targetRevision: 18.2.2
        helm:
          valueFiles:
            - values.yaml
            - "values-{{.nameNormalized}}.yaml"
      destination:
        server: '{{.server}}'
        namespace: whosyourdaddy
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
