apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 7.6.5
    helm:
      valueFiles:
      - $values/values.yaml
      - $values/other-values.yaml
  - repoURL: git@github.com:iveahugeship/minikube.git
    targetRevision: HEAD
    path: clusters/minikube/argocd
    ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
