apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd-sync
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - clusters: {}
  template:
    metadata:
      name: 'argocd-sync-{{.nameNormalized}}'
    spec:
      project: default
      source:
        repoURL: git@github.com:iveahugeship/minikube.git
        targetRevision: HEAD
        path: 'argocd'
        directory:
          recurse: true
      destination:
        server: '{{.server}}'
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
