---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: prometheus
spec:
  interval: 1m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "41.x"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
