---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prometheus
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./apps/monitoring/prometheus
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
